# Generated by Django 5.1.2 on 2024-10-28 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reconhecimento', '0001_initial'),
        ('usuario', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='imagem',
        ),
        migrations.AddField(
            model_name='usuario',
            name='imagens',
            field=models.ManyToManyField(blank=True, to='reconhecimento.imagem'),
        ),
    ]
